M48
; DRILL file {KiCad 7.0.1} date Fri Mar 28 02:09:48 2025
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-03-28T02:09:48+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.950
%
G90
G05
T1
X247.57Y-100.71
T2
X247.57Y-93.36
T0
M30
